import { useRef, useState } from 'react';
import api from '../utils/api';
const TYPES = ['Invoice', 'Warranty', 'Manual', 'Certificate', 'Image', 'Other'];
export default function DocumentManager({ assetId, documents, onChange }) {
  const ref = useRef(); const [type, setType] = useState('Invoice'); const [busy, setBusy] = useState(false);
  async function upload(file) { if (!file) return; setBusy(true); try { const dataUrl = await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)}); await api.uploadDocument(assetId,{name:file.name,type,mimeType:file.type,size:file.size,dataUrl}); onChange(); } catch(e) { alert(e.message || 'Upload failed'); } finally { setBusy(false); ref.current.value=''; } }
  async function remove(id) { if (!window.confirm('Delete this document?')) return; await api.deleteDocument(id); onChange(); }
  return <div className="space-y-3"><div className="flex flex-wrap gap-2"><select value={type} onChange={e=>setType(e.target.value)} className="border rounded-lg px-3 py-2 text-sm"><option disabled>Document type</option>{TYPES.map(t=><option key={t}>{t}</option>)}</select><input ref={ref} type="file" className="hidden" onChange={e=>upload(e.target.files[0])}/><button onClick={()=>ref.current.click()} disabled={busy} className="rounded-lg bg-ink-900 px-3 py-2 text-sm text-white disabled:opacity-50">{busy ? 'Uploading…' : 'Upload document'}</button></div>{documents.length ? <ul className="divide-y divide-gray-100 rounded-lg border">{documents.map(d=><li key={d.id} className="flex items-center justify-between gap-3 p-3 text-sm"><div className="min-w-0"><p className="truncate font-medium text-ink-900">{d.name}</p><p className="text-xs text-gray-400">{d.type} · {Math.round((d.size || 0)/1024)} KB</p></div><div className="flex gap-3"><a className="text-teal-600" href={d.externalUrl || d.dataUrl} target="_blank" rel="noreferrer">Preview</a><button className="text-red-600" onClick={()=>remove(d.id)}>Delete</button></div></li>)}</ul> : <p className="rounded-lg border border-dashed p-5 text-center text-sm text-gray-400">Attach invoices, warranties, manuals, certificates, or images.</p>}</div>;
}
