const HTTP = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL: 500,
};

const ROLES = {
  ADMIN: 'ADMIN',
  ASSET_MANAGER: 'ASSET_MANAGER',
  DEPARTMENT_HEAD: 'DEPARTMENT_HEAD',
  EMPLOYEE: 'EMPLOYEE',
};

const ASSET_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ALLOCATED: 'ALLOCATED',
  RESERVED: 'RESERVED',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  LOST: 'LOST',
  RETIRED: 'RETIRED',
  DISPOSED: 'DISPOSED',
};

const TRANSFER_STATUS = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
};

const MAINTENANCE_STATUS = {
  SCHEDULED: 'SCHEDULED',
  APPROVED: 'APPROVED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const MAINTENANCE_PRIORITY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};

const AUDIT_CYCLE_STATUS = {
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const ASSET_VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  MISSING: 'MISSING',
  DAMAGED: 'DAMAGED',
  DISPOSED: 'DISPOSED',
};

const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
};

const AUDIT_ACTIONS = {
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_STATUS_CHANGED: 'ASSET_STATUS_CHANGED',
  ASSET_ALLOCATED: 'ASSET_ALLOCATED',
  ASSET_RETURNED: 'ASSET_RETURNED',
  ASSET_TRANSFERRED: 'ASSET_TRANSFERRED',
  ASSET_QR_REGENERATED: 'ASSET_QR_REGENERATED',
  TRANSFER_REQUESTED: 'TRANSFER_REQUESTED',
  TRANSFER_APPROVED: 'TRANSFER_APPROVED',
  TRANSFER_REJECTED: 'TRANSFER_REJECTED',
  MAINTENANCE_SCHEDULED: 'MAINTENANCE_SCHEDULED',
  MAINTENANCE_UPDATED: 'MAINTENANCE_UPDATED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  AUDIT_CYCLE_CREATED: 'AUDIT_CYCLE_CREATED',
  AUDIT_CYCLE_COMPLETED: 'AUDIT_CYCLE_COMPLETED',
  AUDIT_ITEM_VERIFIED: 'AUDIT_ITEM_VERIFIED',
  USER_CREATED: 'USER_CREATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',
  VENDOR_CREATED: 'VENDOR_CREATED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

const ENTITY_TYPES = {
  ASSET: 'Asset',
  ALLOCATION: 'Allocation',
  TRANSFER: 'TransferRequest',
  MAINTENANCE: 'MaintenanceRecord',
  BOOKING: 'Booking',
  AUDIT_CYCLE: 'AuditCycle',
  AUDIT_ITEM: 'AuditItem',
  USER: 'User',
  DEPARTMENT: 'Department',
  VENDOR: 'Vendor',
};

const WARRANTY_ALERT_DAYS = { CRITICAL: 7, WARNING: 30, NOTICE: 90 };

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

const BCRYPT_ROUNDS = 12;

const JWT_EXPIRY = '8h';

module.exports = {
  HTTP,
  ROLES,
  ASSET_STATUS,
  TRANSFER_STATUS,
  MAINTENANCE_STATUS,
  MAINTENANCE_PRIORITY,
  BOOKING_STATUS,
  AUDIT_CYCLE_STATUS,
  ASSET_VERIFICATION_STATUS,
  AUDIT_ACTIONS,
  ENTITY_TYPES,
  PAGINATION,
  BCRYPT_ROUNDS,
  JWT_EXPIRY,
  WARRANTY_ALERT_DAYS,
};
