import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Layout from '../components/Layout';
import api from '../utils/api';
export default function AssetScanner(){const video=useRef();const nav=useNavigate();const [message,setMessage]=useState('Point the camera at an AssetFlow QR code.');const [manual,setManual]=useState('');const [active,setActive]=useState(false);const timer=useRef();
 async function resolve(code){if(!code)return;setMessage('Looking up asset…');try{const r=await api.lookupByQR(code.trim());nav(`/assets/${r.data.asset.id}`)}catch{setMessage('That QR code is not an active AssetFlow asset. Try another code.')}}
 async function start(){if(!('BarcodeDetector'in window)){setMessage('Camera decoding is not supported in this browser. Upload a QR image or paste the code.');return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.current.srcObject=stream;setActive(true);const detector=new window.BarcodeDetector({formats:['qr_code']});timer.current=setInterval(async()=>{if(video.current?.readyState>=2){const codes=await detector.detect(video.current);if(codes[0]){stop();resolve(codes[0].rawValue)}}},500)}catch{setMessage('Camera permission was denied or unavailable.')}}
 function stop(){clearInterval(timer.current);const s=video.current?.srcObject;s?.getTracks().forEach(t=>t.stop());setActive(false)} useEffect(()=>()=>stop(),[]);
 async function image(file){if(!file)return;if(!('BarcodeDetector'in window)){setMessage('Image decoding is unavailable in this browser; paste the QR value below.');return}try{const detector=new window.BarcodeDetector({formats:['qr_code']});const bitmap=await createImageBitmap(file);const codes=await detector.detect(bitmap);if(codes[0]) resolve(codes[0].rawValue); else setMessage('No QR code was found in that image.')}catch{setMessage('Unable to read that image.')}}
 return <Layout title="QR Scanner"><div className="mx-auto max-w-2xl space-y-5"><div className="rounded-2xl border bg-white p-6 text-center"><h2 className="text-xl font-semibold text-ink-900">Find an asset instantly</h2><p className="mt-2 text-sm text-gray-500">Scan a printed AssetFlow QR label, upload an image, or enter its code.</p><div className="mx-auto mt-5 aspect-video max-w-lg overflow-hidden rounded-xl bg-gray-900"><video ref={video} autoPlay playsInline className="h-full w-full object-cover"/>{!active&&<div className="flex h-full items-center justify-center text-sm text-gray-400">Camera preview</div>}</div><div className="mt-4 flex flex-wrap justify-center gap-3"><button onClick={active?stop:start} className="rounded-lg bg-ink-900 px-4 py-2 text-sm text-white">{active?'Stop camera':'Use camera'}</button><label className="cursor-pointer rounded-lg border px-4 py-2 text-sm"><input type="file" accept="image/*" className="hidden" onChange={e=>image(e.target.files[0])}/>Upload QR image</label></div><p className="mt-4 text-sm text-gray-500">{message}</p></div><form onSubmit={e=>{e.preventDefault();resolve(manual)}} className="flex gap-2 rounded-xl border bg-white p-4"><input value={manual} onChange={e=>setManual(e.target.value)} placeholder="Paste QR value" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm"/><button className="rounded-lg bg-teal-600 px-4 py-2 text-sm text-white">Open passport</button></form></div></Layout>}
